name: Cancel previous runs

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  cancel:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.6.0
        with:
          workflow_id: 6045716, 6046665
          access_token: ${{ secrets.GITHUB_TOKEN }}
